import { RepDailyStat, RepGoal, RepAlert } from "@/types/performance";

export const START_DATE = new Date().toISOString().split('T')[0];

const buildTrend = (base: number, variance: number) => {
    return Array.from({ length: 7 }).map((_, i) => ({
        date: new Date(Date.now() - (6 - i) * 86400000).toISOString().split('T')[0],
        score: Math.max(30, Math.min(100, Math.floor(base + (Math.random() - 0.5) * variance)))
    }));
};

export const MOCK_PERFORMANCE_DATA: {
    reps: RepDailyStat[];
    goals: RepGoal[];
    alerts: RepAlert[];
    teamAverage: number;
    trend: any[];
} = {
    reps: [
        {
            id: "usr_101",
            userId: "usr_101",
            repName: "Jane Doe",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JD",
            statDate: START_DATE,
            callsTotal: 84,
            callsOutbound: 70,
            callsInbound: 14,
            avgCallDurationSecs: 180,
            meetingsScheduled: 6,
            meetingsCompleted: 4,
            followupsCompleted: 12,
            newLeadsContacted: 22,
            dealsStageAdvanced: 5,
            dealsWon: 2,
            dealsLost: 0,
            revenueClosed: 42000,
            activityCompletionRate: 94.2,
            productivityScore: 96,
            callToMeetingRate: 8.5,
            meetingToProposalRate: 75,
            proposalToWinRate: 50,
            revenuePerCall: 500,
            revenuePerMeeting: 10500,
            dailyRank: 1,
            rankDelta: 1,
            momentum7d: 92,
        },
        {
            id: "usr_102",
            userId: "usr_102",
            repName: "John Smith",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JS",
            statDate: START_DATE,
            callsTotal: 45,
            callsOutbound: 30,
            callsInbound: 15,
            avgCallDurationSecs: 210,
            meetingsScheduled: 3,
            meetingsCompleted: 2,
            followupsCompleted: 8,
            newLeadsContacted: 10,
            dealsStageAdvanced: 2,
            dealsWon: 1,
            dealsLost: 1,
            revenueClosed: 15000,
            activityCompletionRate: 78.5,
            productivityScore: 72,
            callToMeetingRate: 10,
            meetingToProposalRate: 50,
            proposalToWinRate: 33,
            revenuePerCall: 333,
            revenuePerMeeting: 7500,
            dailyRank: 2,
            rankDelta: -1,
            momentum7d: 78,
        },
        {
            id: "usr_103",
            userId: "usr_103",
            repName: "Alice Johnston",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AJ",
            statDate: START_DATE,
            callsTotal: 62,
            callsOutbound: 50,
            callsInbound: 12,
            avgCallDurationSecs: 150,
            meetingsScheduled: 4,
            meetingsCompleted: 3,
            followupsCompleted: 15,
            newLeadsContacted: 18,
            dealsStageAdvanced: 3,
            dealsWon: 0,
            dealsLost: 0,
            revenueClosed: 0,
            activityCompletionRate: 88,
            productivityScore: 68,
            callToMeetingRate: 8,
            meetingToProposalRate: 66,
            proposalToWinRate: 0,
            revenuePerCall: 0,
            revenuePerMeeting: 0,
            dailyRank: 3,
            rankDelta: 0,
            momentum7d: 70,
        },
        {
            id: "usr_104",
            userId: "usr_104",
            repName: "Bob Miller",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BM",
            statDate: START_DATE,
            callsTotal: 15,
            callsOutbound: 10,
            callsInbound: 5,
            avgCallDurationSecs: 90,
            meetingsScheduled: 1,
            meetingsCompleted: 1,
            followupsCompleted: 2,
            newLeadsContacted: 3,
            dealsStageAdvanced: 0,
            dealsWon: 0,
            dealsLost: 2,
            revenueClosed: 0,
            activityCompletionRate: 35,
            productivityScore: 32,
            callToMeetingRate: 10,
            meetingToProposalRate: 0,
            proposalToWinRate: 0,
            revenuePerCall: 0,
            revenuePerMeeting: 0,
            dailyRank: 5,
            rankDelta: -2,
            momentum7d: 45,
        },
        {
            id: "usr_105",
            userId: "usr_105",
            repName: "Charlie Davis",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=CD",
            statDate: START_DATE,
            callsTotal: 55,
            callsOutbound: 40,
            callsInbound: 15,
            avgCallDurationSecs: 185,
            meetingsScheduled: 5,
            meetingsCompleted: 4,
            followupsCompleted: 10,
            newLeadsContacted: 12,
            dealsStageAdvanced: 4,
            dealsWon: 1,
            dealsLost: 0,
            revenueClosed: 21000,
            activityCompletionRate: 85,
            productivityScore: 81,
            callToMeetingRate: 12.5,
            meetingToProposalRate: 80,
            proposalToWinRate: 50,
            revenuePerCall: 381,
            revenuePerMeeting: 5250,
            dailyRank: 4,
            rankDelta: 2,
            momentum7d: 75,
        }
    ],
    goals: [
        { id: "g1", userId: "team", period: "daily", goalType: "calls_total", targetValue: 300 },
        { id: "g2", userId: "team", period: "daily", goalType: "meetings_completed", targetValue: 20 },
        { id: "g3", userId: "team", period: "daily", goalType: "revenue_closed", targetValue: 100000 },
    ],
    alerts: [
        { id: "a1", userId: "usr_104", alertType: "below_threshold", payload: "Bob Miller's activity completion rate is below 50% for 2 consecutive days.", resolved: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
        { id: "a2", userId: "usr_101", alertType: "high_performer", payload: "Jane Doe has closed $42,000 today exceeding her daily goal by 150%.", resolved: false, createdAt: new Date(Date.now() - 7200000).toISOString() },
        { id: "a3", userId: "usr_102", alertType: "zero_activity_3pm", payload: "No outbound calls logged by John Smith since 1:00 PM.", resolved: false, createdAt: new Date(Date.now() - 1800000).toISOString() }
    ],
    teamAverage: 70,
    trend: [
        { date: "Mon", "Jane Doe": 85, "John Smith": 70, "Alice Johnston": 65, "Team Avg": 68 },
        { date: "Tue", "Jane Doe": 88, "John Smith": 75, "Alice Johnston": 60, "Team Avg": 70 },
        { date: "Wed", "Jane Doe": 82, "John Smith": 72, "Alice Johnston": 68, "Team Avg": 69 },
        { date: "Thu", "Jane Doe": 90, "John Smith": 68, "Alice Johnston": 70, "Team Avg": 73 },
        { date: "Fri", "Jane Doe": 95, "John Smith": 80, "Alice Johnston": 75, "Team Avg": 76 },
        { date: "Sat", "Jane Doe": 92, "John Smith": 75, "Alice Johnston": 65, "Team Avg": 71 },
        { date: "Sun", "Jane Doe": 96, "John Smith": 72, "Alice Johnston": 68, "Team Avg": 70 },
    ]
};

export const MOCK_TREND_DATA = [
    { date: "Mon", "Jane Doe": 85, "John Smith": 70, "Alice Johnston": 65, "Team Avg": 68 },
    { date: "Tue", "Jane Doe": 88, "John Smith": 75, "Alice Johnston": 60, "Team Avg": 70 },
    { date: "Wed", "Jane Doe": 82, "John Smith": 72, "Alice Johnston": 68, "Team Avg": 69 },
    { date: "Thu", "Jane Doe": 90, "John Smith": 68, "Alice Johnston": 70, "Team Avg": 73 },
    { date: "Fri", "Jane Doe": 95, "John Smith": 80, "Alice Johnston": 75, "Team Avg": 76 },
    { date: "Sat", "Jane Doe": 92, "John Smith": 75, "Alice Johnston": 65, "Team Avg": 71 },
    { date: "Sun", "Jane Doe": 96, "John Smith": 72, "Alice Johnston": 68, "Team Avg": 70 },
];
